#激活哪一个环境的配置文件
#公共配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: outsidemaster

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
# jdbc_config datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.h2.Driver
      url: "jdbc:h2:file:~/tmp/outsidemaster"
      username: sa
      password: sa
    
      validation-query: select 1
      validation-interval: 30000
      initial-size: 3
      max-active: 100
      min-idle: 10
      time-between-eviction-runs-millis: 30000
      remove-abandoned: true
      remove-abandoned-timeout: 60
      suspect-timeout: 60
      log-abandoned: false
      abandon-when-percentage-full: 50
      min-evictable-idle-time-millis: 60000
      testOnBorrow: true
      testWhileIdle: true
      testOnReturn: false
        
    # 配置获取连接等待超时的时间
      max-wait: 60000
    # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
    # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      
      aop-patterns: com.ebizprise.das.web.controller.v1.*
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters: stat,wall,slf4j
    # 配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
        principal-session-name: NXSESSIONID
        principal-cookie-name: _ga
        profile-enable: true
    # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        
server:
  servlet:
    context-path: /${spring.application.name}/api
  port: 8094
  tomcat:
    uri-encoding: UTF-8
  
info:
  desciption: DAS web
  component: Web Server

management:
#  port: 8081
#  context-path: /manage
  security:
    enabled: false

recmdapi:
  recmdCustProdList: http://127.0.0.1:8092/recmd/api/v1/recmdCustProdList/
  recmdCustGroupProdList: http://127.0.0.1:8092/recmd/api/v1/recmdCustGroupProdList/

code:
  errCode:
    weatherErrorCode: ERR048
    cityMappingErrorCode: ERR051
    holidayErrorCode: ERR052
  mailCode:
    filecalendarDataCode: MAIL022

weather:
  HIGH_TEMPERATURE: HIGH_TEMPERATURE
  LOW_TEMPERATURE: LOW_TEMPERATURE
  WEATHER_CONDITION: WEATHER_CONDITION


fastjson:
# 使用默认属性首字母
  compatibleWithJavaBean: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

baseUrl:
  engineUrl: http://192.168.128.23:8089/?bid=
  apiUrl: http://218.210.49.243:8080
  dbUrl: http://127.0.0.1:8076
  
  syncCityList: dev
  syncCities: 1
  syncEnable: true
  syncServer: dev
  syncUrl1: http://127.0.0.1:8075
  syncUrl2: http://127.0.0.1:8075
  syncUrl3: http://192.168.128.23:8080
  
scheduledtasks:
  trigtime: "0/3 * * * * ?"