#激活哪一个环境的配置文件
#公共配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: outsidemaster

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:h2:file:~/tmp/outsidemaster"
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    
server:
  context-path: /${spring.application.name}/api
  port: 8094
  tomcat:
    uri-encoding: UTF-8
  
info:
  desciption: DAS web
  component: Web Server

management:
#  port: 8081
#  context-path: /manage
  security:
    enabled: false

recmdapi:
  recmdCustProdList: http://127.0.0.1:8092/recmd/api/v1/recmdCustProdList/
  recmdCustGroupProdList: http://127.0.0.1:8092/recmd/api/v1/recmdCustGroupProdList/

code:
  errCode:
    weatherErrorCode: ERR048
    cityMappingErrorCode: ERR051
    holidayErrorCode: ERR052
  mailCode:
    filecalendarDataCode: MAIL022

weather:
  HIGH_TEMPERATURE: HIGH_TEMPERATURE
  LOW_TEMPERATURE: LOW_TEMPERATURE
  WEATHER_CONDITION: WEATHER_CONDITION


fastjson:
# 使用默认属性首字母
  compatibleWithJavaBean: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

baseUrl:
  engineUrl: http://192.168.128.23:8089/?bid=
  apiUrl: http://218.210.49.243:8080
  dbUrl: http://127.0.0.1:8076
  
  syncCityList: dev
  syncCities: 1
  syncEnable: true
  syncServer: dev
  syncUrl1: http://127.0.0.1:8075
  syncUrl2: http://127.0.0.1:8075
  syncUrl3: http://192.168.128.23:8075
  
scheduledtasks:
  trigtime: "0/3 * * * * ?"